### ISSUE TITLE
add option to not de-duplicate for firefox containers

### ISSUE THREAD

**Issue by fawaf** [brcontainer/prevent-duplicate-tabs#10]
otherwise, one cannot open the same link in different containers.

**Comment by brcontainer** [comment]
@fawaf container support added, details in: https://github.com/brcontainer/prevent-duplicate-tabs/commit/7bb6ab6e74dda36dd5a6b8008758f5b386c7d3f9

Update in firefox add-ons: https://addons.mozilla.org/pt-BR/firefox/addon/smart-prevent-duplicate-tabs/

for use this open the popup-menu and enable this option:

![enable containers for diff tabs](https://user-images.githubusercontent.com/4368952/103067371-80e90600-4599-11eb-9501-93f3d16a25d2.png)

**Comment by fawaf** [comment]
confirmed working. thanks!

**Comment by brcontainer** [comment]
@fawaf Since you forked the project without modification or support (code improvements) any back, how does that give strength to the object of the project to be **open-source** collaborating (if possible) with improvements in translations? See details in https://github.com/brcontainer/prevent-duplicate-tabs#languages and https://github.com/brcontainer/prevent-duplicate-tabs/tree/master/chrome/_locales

I have no knowledge of other languages, if you find texts that can be improved your help is welcome. Thanks.
