### ISSUE TITLE
"Ignore Host" Not Preserving

### ISSUE THREAD

**Issue by codemonies** [brcontainer/prevent-duplicate-tabs#14]
Hello,

It seems I have to constantly specify "ignore this host".

Is there a way to preserve the list of ignored hosts? Does it only hold as long as the original tab that whitelisted the host remains open?

Thanks!

**Comment by brcontainer** [comment]
@natesreich Hi! I found the problem. Thanks for reporting.
I am providing the correction and until tomorrow it will be available.

**Comment by codemonies** [comment]
Thanks for the quick response!

I am using 0.7.2 as that's the latest version in the Chrome store. 

The issue appears to be intermittent. Let me try to replicate the issue and then share the details here. For now, until I can consistently do so, I'll go ahead and close this issue.

**Comment by brcontainer** [comment]
@natesreich No need, I was able to replicate, it happens when you do it in two different tabs, even if from different domains, something is overwriting the storage in this process, making the data go rough, I'm already finishing the corrections.

Thank you very much for reporting this bug! Once it's available you notice.

**Comment by codemonies** [comment]
Glad to hear I'm not going crazy! 😂 Thank you for your hard work!

**Comment by brcontainer** [comment]
@natesreich released 0.7.4 version! Fixed bug in "ignore URL and HOST"
