### ISSUE TITLE
[Feature] Show current count of duplicates under each type Action

### ISSUE THREAD

**Issue by hneiva** [brcontainer/prevent-duplicate-tabs#19]
Would be nice to have a count of duplicates
![image](https://user-images.githubusercontent.com/3451557/172900973-4d7a2e9c-9208-4f19-8dd5-8081bbd4170c.png)

Maybe under each header, show `Number of duplicate tabs: XXX` or `XXX duplicate tabs`
It's informative, and helps the user decide if they are clicking the right button.

**Comment by brcontainer** [comment]
The purpose of prevent-duplicate-tabs is to prevent duplicates, so there is no way to show a counter.

Anyway the "Actions" area is about actions on the domain or full url, where you can set to disable the action to prevent duplicates.

If I didn't understand something, don't comment. I'm grateful for the feedback.

Note: I'm working on an improvement so that pages with forms filled by human action (interaction) are not closed, regardless of the settings in prevent-duplicate-tabs.

**Comment by hneiva** [comment]
Yeah, now I understand a little bit better how the app works.

At first I thought only URLs that you selected would be auto-closed (whitelisting), which my comment would make sense; but the app works in a close all except selected (blacklisting).

Thanks for the response!
Cheers
