### ISSUE TITLE
This addon close all my loading tabs while I open them with mid-click

### ISSUE THREAD

**Issue by ghost** [brcontainer/prevent-duplicate-tabs#2]
plz fix

**Comment by brcontainer** [comment]
@swos0000 thanks! I'll fix it today.

**Comment by 1024mb** [comment]
Same is happening to me. It seems that  is because Firefox sometimes load first the tab with about:blank and then loads the website, so a whitelist option would be a quick workaround I think.

**Comment by brcontainer** [comment]
@1024mb thanks i'will fix.

**Comment by Taranchuk** [comment]
Same problem today. Firefox 64.0.2.

**Comment by brcontainer** [comment]
@Taranchuk @swos0000 fixed in https://github.com/brcontainer/prevent-duplicate-tabs/commit/40998d53369fe764d7a22d0f7acbd469c0882fd1#diff-7f123f67b412c67f3d4bc4b6dce417e3R21

- Available for [Chrome](https://chrome.google.com/webstore/detail/prevent-duplicate-tabs/eednccpckdkpojaiemedoejdngappaag)
- Available for [Firefox](https://addons.mozilla.org/en-US/firefox/addon/smart-prevent-duplicate-tabs/)
- Available [MS Edge (chromium)](https://microsoftedge.microsoft.com/addons/detail/iijplllphnkkeepcinimpjobncicbbmb)
- Add-on for Opera is NOT available, but available for Opera Next and Opera Developer
