### ISSUE TITLE
An option for Workspaces to not close tabs when the tab is locked.  

### ISSUE THREAD

**Issue by powellce** [brcontainer/prevent-duplicate-tabs#33]
**Is your feature request related to a problem? **
Workspaces are a new feature and prevent-duplicate-tabs could be updated to align with the new function in Workspaces. A locked tab in a Workspace is locked so that it never gets closed and persists across restarts.  After carefully setting up a workspace, my locked tabs were closing, and I just now figured out that it's this extension that is overriding the Workspace intended design.  I don't think there's a way to configure the extension for this new function.

**Describe the solution you'd like**
I would like an option "Don't close locked Workspace tabs"

**Describe alternatives you've considered**
Locking a tab in a workspace by definition means "Don't close this tab", so, alternatively, the extension could just simply never close the locked tab.  That way, a toggle option would not be needed.  It could just submit to the intent of the design of the Workspace function -- to not close locked tabs.

**Additional context**
For example:   I carefully set up a research strategy where tab management is made possible by this extension.  Each group had two or more spouse couples.  Then I locked the tabs.  But as I was working, the tabs for the people were disappearing, even though they were locked.

<img width="229" alt="Screenshot 2023-07-14 231140" src="https://github.com/brcontainer/prevent-duplicate-tabs/assets/30633789/5c47a241-c98a-441d-b3e1-1dfb1fad85d8">

**Comment by brcontainer** [comment]
In version [0.8.0](https://github.com/brcontainer/prevent-duplicate-tabs/tree/0.8.0), we have already differentiated group tabs from normal tabs.

Note that I am applying rigorous and personal tests to the new version before releasing it in the stores.

**Comment by powellce** [comment]
This request is regardless of Groups.  In the first example, all the tabs are in groups, but that is coincidental and regardless of my request.  The request is for "Locked" tabs, a feature of Edge Workspaces.   Here's another example where tabs are locked and not grouped.

This shows tabs in a Workspace named "Evaline JONES Ezell diaspora", with no groups, and all tabs unlocked showing the usual "x" icon to close-tab.
<img width="307" alt="Screenshot 2023-07-17 075923" src="https://github.com/brcontainer/prevent-duplicate-tabs/assets/30633789/3abcd699-8ea4-4384-93f7-e4653f8f38d5">

Select the tabs and then right-click the selected tabs to see the option to "Lock the selected tabs":
<img width="386" alt="Screenshot 2023-07-17 080004" src="https://github.com/brcontainer/prevent-duplicate-tabs/assets/30633789/eca925ca-e327-45cb-8a98-a4b659f65f2b">

The selected tabs now show the Lock icon instead of the "X" icon.  
<img width="239" alt="Screenshot 2023-07-17 080019" src="https://github.com/brcontainer/prevent-duplicate-tabs/assets/30633789/47062a83-9d89-44ec-8221-9f6863f6718f">

The request is to not close the locked tabs, regardless of Groups. 
<img width="239" alt="Screenshot 2023-07-17 081920" src="https://github.com/brcontainer/prevent-duplicate-tabs/assets/30633789/05a774e8-378d-4590-91e3-013a42dcd597">
 
More about Edge Workspaces:  The creator of a Workspace can invite other users to work together in the Workspace, sharing all the tabs.  The tab can be locked on a URL so that if the URL changes on that locked tab, users can click the tab icon to "Return tab to locked URL".  That makes the locked URL always available through the back button or through the "Return tab to locked URL" button and that locked tab cannot be accidentally closed. The prevent-duplicate-tabs, however, overrides this new feature and this request is to not close locked tabs.

When you create a Workspace, Microsoft explains it like this:  edge://welcome-to-your-workspace/
<img width="919" alt="Screenshot 2023-07-17 084006" src="https://github.com/brcontainer/prevent-duplicate-tabs/assets/30633789/b9913a40-eeca-4c76-aa35-12ccd42822ad">

**Comment by brcontainer** [comment]
Hello @powellce 

I had already understood, it is necessary to understand that the "lock" and "Workspaces" are resources still limited to the "public preview", it is a new resource and is not yet part of the extensions API (https://developer.chrome.com/docs/extensions/reference/tabs/), the only way to identify details about browser tabs and windows is if the API supports it, but it still does not.

That's why I previously suggested an alternative, using groups, and thus avoiding duplication within groups, which will be ignored in other groups or outside the group, so it will work well as an alternative.

When projects that use Chromium (like Edge, Chrome, and Brave) update the API so I can have the information about "Lock" in [`chrome.tabs.Tab`](https://developer.chrome.com/docs/extensions/reference/tabs/#type-Tab), then I will release the improved feature.

**Edited:**

New ideas are great, but functionalities depend on the native API "chrome.tabs.Tab" to expose the information that allows the idea to be developed, there is no other way to get information from the tabs, it all depends on the native API. At the moment the available properties are described in:

- https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/Tab
- https://developer.chrome.com/docs/extensions/reference/tabs/#type-Tab

I appreciate your understanding.

**Comment by powellce** [comment]
Excellent.  Thank you.

🪶
________________________________
